title = "ePANDA configuration"

[waste_vials]

    [waste_vials.1]
    name = "waste_vial_1"
    contents = "waste"
    position = [x,y,z]
    volume = 1000

    [waste_vials.2]
    name = "waste_vial_2"
    contents = "waste"
    position = [x,y,z]
    volume = 1000

    [waste_vials.3]
    name = "waste_vial_3"
    contents = "waste"
    position = [x,y,z]
    volume = 1000

    [waste_vials.4]
    name = "waste_vial_4"
    contents = "waste"
    position = [x,y,z]
    volume = 1000

    [waste_vials.5]
    name = "waste_vial_5"
    contents = "waste"
    position = [x,y,z]
    volume = 1000

    [waste_rinse_vials.1]
    name = "rinse_vial_1"
    contents = "rinse"
    position = [x,y,z]
    volume = 1000

    [waste_rinse_vials.2]
    name = "rinse_vial_1"
    contents = "rinse"
    position = [x,y,z]
    volume = 1000

    [waste_rinse_vials.3]
    name = "rinse_vial_1"
    contents = "rinse"
    position = [x,y,z]
    volume = 1000


